### POST localhost:7070/project 프로젝트 등록 1
POST http://localhost:7070/project
Content-Type: application/json

{
  "project_name": "프로젝트1",
  "project_state": "ACTIVE"
}

### POST localhost:7070/project 프로젝트 등록 2
POST http://localhost:7070/project
Content-Type: application/json

{
  "project_name": "프로젝트2",
  "project_state": "ACTIVE"
}

### POST localhost:7070/project/{userId} 프로젝트 멤버 등록
POST http://localhost:7070/project/user1
Content-Type: application/json

{
  "project_id": 1,
  "project_manager": false
}

### POST localhost:7070/project/{userId} 프로젝트 멤버 등록
POST http://localhost:7070/project/user2
Content-Type: application/json

{
  "project_id": 1,
  "project_manager": false
}

### POST localhost:7070/project/{userId} 프로젝트 멤버 등록
POST http://localhost:7070/project/user3
Content-Type: application/json

{
  "project_id": 1,
  "project_manager": true
}

### POST localhost:7070/project/{userId} 프로젝트 멤버 등록
POST http://localhost:7070/project/user1
Content-Type: application/json

{
  "project_id": 2,
  "project_manager": false
}

### GET localhost:7070/project/{userId} 회원이 속한 Project 목록 조회
GET http://localhost:7070/project/user1

### PUT localhost:7070/project/{projectId} 프로젝트 수정
PUT http://localhost:7070/project/1
Content-Type: application/json

{
  "project_name": "프로젝트명 변경",
  "project_state": "COMPLETED"
}

### DELETE localhost:7070/project/{projectId} 프로젝트 삭제
DELETE http://localhost:7070/project/1



