### 등록
POST localhost:7070/project/1/task/1/projectTag
Content-Type: application/json

{
  "tagId": 1,
  "taskId": 1
}

### 등록
POST localhost:7070/project/1/task/1/projectTag
Content-Type: application/json

{
  "tagId": 2,
  "taskId": 1
}

### 전체 조회
GET localhost:7070/project/1/task/1/projectTag


### 삭제
DELETE localhost:7070/project/1/task/1/projectTag/1