### 등록
POST localhost:7070/project/1/task
Content-Type: application/json

{
  "task_title": "task test1",
  "task_description": "This is description"
}

### 등록
POST localhost:7070/project/1/task
Content-Type: application/json

{
  "task_title": "2222",
  "task_description": "This is description2"
}

### 단일 조회
GET localhost:7070/project/1/task/1

### 전체 조회
GET localhost:7070/project/1/task

### 수정
PUT localhost:7070/project/1/task/1
Content-Type: application/json

{
  "task_title": "task edit",
  "task_description": "hello"
}

### 삭제
DELETE localhost:7070/project/1/task/1