### POST localhost:7070/project 프로젝트 등록 1
POST http://localhost:7070/project
Content-Type: application/json

{
  "projectName": "프로젝트1",
  "projectState": "ACTIVE"
}

### POST localhost:7070/project 프로젝트 등록 2
POST http://localhost:7070/project
Content-Type: application/json

{
  "projectName": "프로젝트2",
  "projectState": "ACTIVE"
}

### POST localhost:7070/project/{projectId}/members 프로젝트 멤버 등록
POST http://localhost:7070/project/1/members
Content-Type: application/json

{
  "userId": "user1",
  "projectManager": false
}

### POST localhost:7070/project/{projectId}/members 프로젝트 멤버 등록
POST http://localhost:7070/project/2/members
Content-Type: application/json

{
  "userId": "user1",
  "projectManager": false
}

### POST localhost:7070/project/{projectId}/members 프로젝트 멤버 등록
POST http://localhost:7070/project/1/members
Content-Type: application/json

{
  "userId": "user2",
  "projectManager": false
}

### POST localhost:7070/project/{projectId}/members 프로젝트 멤버 등록
POST http://localhost:7070/project/1/members
Content-Type: application/json

{
  "userId": "user3",
  "projectManager": true
}

### POST localhost:7070/project/{projectId}/members 프로젝트 멤버 등록
POST http://localhost:7070/project/1/members
Content-Type: application/json

{
  "userId": "user4",
  "projectManager": false
}

### GET localhost:7070/project/members/{userId} 회원이 속한 Project 목록 조회
GET http://localhost:7070/project/members/user1

### PUT localhost:7070/project/{projectId} 프로젝트 수정
PUT http://localhost:7070/project/1
Content-Type: application/json

{
  "projectName": "프로젝트명 변경",
  "projectState": "COMPLETED"
}

### GET localhost:7070/project/{projectId} 프로젝트 조회
GET http://localhost:7070/project/1

### DELETE localhost:7070/project/{projectId} 프로젝트 삭제
DELETE http://localhost:7070/project/1



