### 등록
POST localhost:7070/project/1/tag
Content-Type: application/json

{
  "tag_name": "개발"
}

### 등록2
POST localhost:7070/project/1/tag
Content-Type: application/json

{
  "tag_name": "디자인"
}

### 단일 조회
GET localhost:7070/project/1/tag/1

### 전체 조회
GET localhost:7070/project/1/tag


### 수정
PUT localhost:7070/project/1/tag/1
Content-Type: application/json

{
  "tag_name": "개발부서"
}

### 삭제
DELETE localhost:7070/project/1/tag/2
