spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/nhn_exam_102
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nhn_exam_102
    password: xV2paoph!

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect