spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/nhn_academy_106
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: nhn_academy_106
    password: oD8vlmwi!
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        auto_quote_keyword: true
    hibernate:
      ddl-auto: update
#      ddl-auto: validate