spring:
  application:
    name: TaskAPI
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: dev
    group:
      dev: application-dev
      prod: application-prod

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace

server:
  port: 7070